import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Image from 'next/image';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased relative h-screen w-screen`}
      >
        <div className='absolute inset-0 -z-30'>
          <Image
            src='/webBg.jpg'
            alt='background'
            layout='fill'
            objectFit='cover'
            quality={100}
            priority
          />
        </div>

        {children}
      </body>
    </html>
  );
}
